name: Full MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Configure DVC Remote
        run: |
          dvc remote add -f origin https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/churn-mlops.dvc
          dvc remote default origin

      - name: Authenticate DVC
        run: |
          dvc remote modify origin auth basic
          dvc remote modify origin user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull Data
        run: dvc pull

      - name: Run DVC Pipeline
        run: dvc repro

      - name: Push Data
        run: dvc push

      - name: Build Docker Image

        run: docker build -t churn-api .
