name: Full MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[s3]"

      - name: Configure DVC Remote
        run: |
          dvc remote add -f origin https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/churn-mlops.dvc
          dvc remote default origin
          dvc remote modify origin auth basic
          dvc remote modify origin user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin password ${{ secrets.DAGSHUB_TOKEN }}

      # 🔥 Pull existing data first
      - name: Pull DVC Data
        run: dvc pull --force

      # 🔥 Run pipeline
      - name: Run DVC Pipeline
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: dvc repro

      # 🔥 Push updates (only if something changed)
      - name: Push DVC Artifacts
        run: dvc push